--- # document start

################
# CONFIG FILE  #
################

desirated_framerate: 60
display_shell_interface: False
is_zmq_api_enabled: True

audio_ports:
  - name: Loopback Audio d
    min_frequency: 200
    max_frequency: 12000
  - name:Built-in Microphonedawdawd
    min_frequency: 200
    max_frequency: 12000

strips:
  - name: Angles
    serial_port_name: /dev/tty.usbserial-A50285BI

    midi_ports_for_visualization:
      - 'Audio2Led Synthd'
      - 'LPK25'
    midi_ports_for_changing_mode:
      - 'Audio2Led ChangeMod Center'

    active_state_index: 0

    original_physical_shape:
      - 34
      - 52
      - 50

    scene:
      size:
        width: 300
        height: 170
        scale: 1.5

      shapes:
        - svg_string: 'M0,0 0,100 T75,175'
          pixel_range: [86, 136]
          offset: [0, 0]
        - svg_string: 'M50,0 50,75 T100,125'
          pixel_range: [34, 86]
          offset: [0, 0]
        - svg_string: 'M100,0 100,50 T125,75'
          pixel_range: [0, 34]
          offset: [0, 0]
        - svg_string: 'M300,0 300,100 T225,175'
          pixel_range: [86, 136]
          offset: [0, 0]
        - svg_string: 'M250,0 250,75 T200,125'
          pixel_range: [34, 86]
          offset: [0, 0]
        - svg_string: 'M200,0 200,50 T175,75'
          pixel_range: [0, 34]
          offset: [0, 0]
    states:
      - name: 'Classic energy'
        active_visualizer_effect: energy
        active_propagation_curve: ease_in

        active_audio_channel_index: 0
        audio_samples_filter_min: 0
        audio_samples_filter_max: 24
        audio_decay: 0.1
        audio_gain: 1
        active_color_scheme_index: 0
        color_schemes:
          - - red
            - green
            - blue
          - - red
          - - green
          - - blue

        is_reverse: False
        is_mirror: False
        division_value: 0
        time_interval: 10
        chunk_size: 50
        blur_value: 1.0
        max_brightness: 100

      - name: 'Classic scroll'
        active_visualizer_effect: scroll
        active_propagation_curve: ease_in

        active_audio_channel_index: 1
        audio_samples_filter_min: 0
        audio_samples_filter_max: 24
        audio_decay: 0.1
        audio_gain: 1

        active_color_scheme_index: 0
        color_schemes:
          - - red
            - blue
          - - red
            - green
            - blue
        is_reverse: False
        is_mirror: True
        division_value: 0
        time_interval: 10
        chunk_size: 50
        blur_value: 0.1
        max_brightness: 100

      - name: 'Piano note'
        active_visualizer_effect: piano_scroll
        active_propagation_curve: ease_in

        active_audio_channel_index: 0
        audio_samples_filter_min: 0
        audio_decay: 0.1
        audio_gain: 1
        audio_samples_filter_max: 24

        active_color_scheme_index: 0
        color_schemes:
          - - red
            - blue
          - - red
            - green
            - blue
        is_reverse: False
        is_mirror: False
        division_value: 0
        time_interval: 10
        chunk_size: 50
        blur_value: 1.1
        max_brightness: 100
... # document end
