--- # document start

################
# CONFIG FILE  #
################

desirated_framerate: 60
display_shell_interface: False
is_zmq_api_enabled: True

audio_ports:
  - name: Loopback Audio
    min_frequency: 200
    max_frequency: 12000
  - name: Built-in Microphone
    min_frequency: 200
    max_frequency: 12000

state_groups:
  - [1, 2]

strips:
  - name: Bar
    serial_port_name: /dev/tty.usbserial-A50285BI
    midi_ports_for_visualization:
      - 'Audio2Led Synth'
      # - 'LPK25'
    midi_ports_for_changing_mode:
      - 'Audio2Led ChangeMod Side'
      # - 'LPK25'
    active_state_index: 0
    original_physical_shape:
      - 80

    scene:
      size:
        width: 750
        height: 270
        scale: 3

      shapes:
        - svg_string: 'M28.636 35.17H.142L20.207.415 40.272 35.17h-3.03'
          pixel_range: [0, 80]
          offset: [0, 0]

        - svg_string: 'M75.842 34.245H54.309V.925h33.319v33.32h-3.19'
          pixel_range: [0, 80]
          offset: [0, 0]

        - svg_string: 'M174.813 35.09l-10.728.055-7.112-21.525L175.243.205l18.404 13.235-6.896 21.59-3.445.015'
          pixel_range: [0, 80]
          offset: [0, 0]

        - svg_string: 'M122.79 34.845l-8.325.055-10.119-17.26L114.237.245l20.009-.13 10.118 17.26-9.891 17.395-3.114.02'
          pixel_range: [0, 80]
          offset: [0, 0]

  - name: Bar2
    serial_port_name: /dev/tty.usbserial-A50285BI2
    midi_ports_for_visualization:
      - 'Audio2Led Synth'
      # - 'LPK25'
    midi_ports_for_changing_mode:
      - 'Audio2Led ChangeMod Side'
      # - 'LPK25'
    active_state_index: 0
    original_physical_shape:
      - 80

    scene:
      size:
        width: 750
        height: 270
        scale: 3

      shapes:
        - svg_string: 'M28.636 35.17H.142L20.207.415 40.272 35.17h-3.03'
          pixel_range: [0, 80]
          offset: [0, 0]

        - svg_string: 'M75.842 34.245H54.309V.925h33.319v33.32h-3.19'
          pixel_range: [0, 80]
          offset: [0, 0]

        - svg_string: 'M174.813 35.09l-10.728.055-7.112-21.525L175.243.205l18.404 13.235-6.896 21.59-3.445.015'
          pixel_range: [0, 80]
          offset: [0, 0]

        - svg_string: 'M122.79 34.845l-8.325.055-10.119-17.26L114.237.245l20.009-.13 10.118 17.26-9.891 17.395-3.114.02'
          pixel_range: [0, 80]
          offset: [0, 0]
    original_physical_shape:
      - 80

    scene:
      size:
        width: 100
        height: 100
        scale: 1

      shapes:
        # - svg_string: 'M50, 50m -75, 0a 75,75 0 1,0 150,0a 75,75 0 1,0 -150,0'
        #   pixel_range: [0, 80]
        #   offset: [0, 0]

        - svg_string: 'M0, -100 150, 150'
          pixel_range: [0, 80]
          offset: [50, -15]
        - svg_string: 'M150, 150 -150, 150'
          pixel_range: [0, 80]
          offset: [50, -15]
        - svg_string: 'M-150, 150 0,-100'
          pixel_range: [0, 80]
          offset: [50, -15]

        - svg_string: 'M0, 0 0,100'
          pixel_range: [0, 80]
          offset: [0, 0]

        - svg_string: 'M0, 100 100,100'
          pixel_range: [0, 80]
          offset: [0, 0]

        - svg_string: 'M100, 100 100,0'
          pixel_range: [0, 80]
          offset: [0, 0]

        - svg_string: 'M100, 0 0,0'
          pixel_range: [0, 80]
          offset: [0, 0]


states:
  - name: 'Classic energy'
    active_visualizer_effect: channel_flash
    active_propagation_curve: ease_in

    active_audio_channel_index: 0
    audio_samples_filter_min: 0
    audio_samples_filter_max: 24
    audio_decay: 0.1
    audio_gain: 1
    active_color_scheme_index: 0
    color_schemes:
      - - red
        - green
        - blue
      - - red
        - green
      - - blue

    is_reverse: False
    is_mirror: False
    division_value: 0
    time_interval: 10
    chunk_size: 50
    blur_value: 1.0
    max_brightness: 100
  - name: 'Classic energy 2'
    active_visualizer_effect: scroll
    active_propagation_curve: ease_in

    active_audio_channel_index: 0
    audio_samples_filter_min: 0
    audio_samples_filter_max: 24
    audio_decay: 0.1
    audio_gain: 1
    active_color_scheme_index: 0
    color_schemes:
      - - red
        - green
        - blue
      - - red
        - green
      - - blue

    is_reverse: False
    is_mirror: False
    division_value: 0
    time_interval: 10
    chunk_size: 50
    blur_value: 1.0
    max_brightness: 100
... # document end
