file_name: /Users/thibaudfrere/Documents/music-2-led/backend/CONFIG.yml
desirated_framerate: 60
display_shell_interface: false
is_zmq_api_enabled: true
audio_ports:
- max_frequency: 12000
  min_frequency: 200
  name: Loopback Audio
- max_frequency: 12000
  min_frequency: 200
  name: Built-in Microphone
strips:
- name: Angles
  serial_port_name: /dev/tty.usbserial-4
  is_online: false
  midi_ports_for_changing_mode:
  - Audio2Led ChangeMod Center
  midi_ports_for_visualization:
  - Audio2Led Synth
  - LPK25
  original_physical_shape:
  - 34
  - 52
  - 50
  scene:
    shapes:
    - offset:
      - 0
      - 0
      pixel_range:
      - 86
      - 136
      svg_string: M0,0 0,100 T75,175
    - offset:
      - 0
      - 0
      pixel_range:
      - 34
      - 86
      svg_string: M50,0 50,75 T100,125
    - offset:
      - 0
      - 0
      pixel_range:
      - 0
      - 34
      svg_string: M100,0 100,50 T125,75
    - offset:
      - 0
      - 0
      pixel_range:
      - 86
      - 136
      svg_string: M300,0 300,100 T225,175
    - offset:
      - 0
      - 0
      pixel_range:
      - 34
      - 86
      svg_string: M250,0 250,75 T200,125
    - offset:
      - 0
      - 0
      pixel_range:
      - 0
      - 34
      svg_string: M200,0 200,50 T175,75
    size:
      height: 170
      scale: 1.2
      width: 300
  states:
  - name: Forevermore
    active_audio_channel_index: 0
    audio_samples_filter_min: 0
    audio_samples_filter_max: 3
    audio_gain: 0.1
    audio_decay: 0.1
    division_value: 0
    active_visualizer_effect: energy
    max_brightness: 138
    time_interval: 120
    chunk_size: 5
    blur_value: 0.6
    is_reverse: true
    is_mirror: false
    active_color_scheme_index: 10
    color_schemes:
    - - red
      - green
      - blue
    - - '#2a04ff'
      - '#ff9604'
    - - '#02e6ff'
      - '#ff4a02'
    - - '#2bff01'
      - '#ff0127'
    - - '#fff700'
      - '#f700ff'
    - - red
    - - green
    - - blue
    - - yellow
    - - pink
    - - '#ee00ac'
      - blue
    - - '#BE008A'
      - green
  - name: Hypervoid
    active_audio_channel_index: 0
    audio_samples_filter_min: 0
    audio_samples_filter_max: 24
    audio_gain: 1
    audio_decay: 0.1
    division_value: 0
    active_visualizer_effect: energy
    max_brightness: 120
    time_interval: 238
    chunk_size: 5
    blur_value: 0.1
    is_reverse: true
    is_mirror: false
    active_color_scheme_index: 10
    color_schemes:
    - - red
      - green
      - blue
    - - '#2a04ff'
      - '#ff9604'
    - - '#02e6ff'
      - '#ff4a02'
    - - '#2bff01'
      - '#ff0127'
    - - '#fff700'
      - '#f700ff'
    - - red
    - - green
    - - blue
    - - yellow
    - - pink
    - - '#ee00ac'
      - blue
    - - '#BE008A'
      - green
  - &id001
    name: test
    active_audio_channel_index: 0
    audio_samples_filter_min: 0
    audio_samples_filter_max: 24
    audio_gain: 1
    audio_decay: 0.1
    division_value: 0
    active_visualizer_effect: piano_scroll
    max_brightness: 120
    time_interval: 0
    chunk_size: 5
    blur_value: 0.5
    is_reverse: false
    is_mirror: false
    active_color_scheme_index: 10
    color_schemes:
    - - red
      - green
      - blue
    - - '#2a04ff'
      - '#ff9604'
    - - '#02e6ff'
      - '#ff4a02'
    - - '#2bff01'
      - '#ff0127'
    - - '#fff700'
      - '#f700ff'
    - - red
    - - green
    - - blue
    - - yellow
    - - pink
    - - '#ee00ac'
      - blue
    - - '#BE008A'
      - green
  active_state_index: 2
  active_state: *id001
- name: Top bar
  serial_port_name: /dev/tty.usbserial-A50285BI
  is_online: false
  midi_ports_for_changing_mode:
  - Audio2Led ChangeMod TopBar
  midi_ports_for_visualization:
  - Audio2Led Synth
  - LPK25
  original_physical_shape:
  - 80
  scene:
    shapes:
    - offset:
      - 0
      - 0
      pixel_range:
      - 0
      - 80
      svg_string: M0,-20 T300,-20
    size:
      height: 170
      scale: 1.2
      width: 300
  states:
  - name: Test2
    active_audio_channel_index: 0
    audio_samples_filter_min: 0
    audio_samples_filter_max: 24
    audio_gain: 0.1
    audio_decay: 0.1
    division_value: 0
    active_visualizer_effect: energy
    max_brightness: 138
    time_interval: 0
    chunk_size: 5
    blur_value: 8.0
    is_reverse: false
    is_mirror: true
    active_color_scheme_index: 10
    color_schemes:
    - - red
      - green
      - blue
    - - '#2a04ff'
      - '#ff9604'
    - - '#02e6ff'
      - '#ff4a02'
    - - '#2bff01'
      - '#ff0127'
    - - '#fff700'
      - '#f700ff'
    - - red
    - - green
    - - blue
    - - yellow
    - - pink
    - - '#ee00ac'
      - blue
    - - '#BE008A'
      - green
  - name: test
    active_audio_channel_index: 0
    audio_samples_filter_min: 0
    audio_samples_filter_max: 24
    audio_gain: 0.1
    audio_decay: 0.1
    division_value: 0
    active_visualizer_effect: spectrum
    max_brightness: 255
    time_interval: 0
    chunk_size: 50
    blur_value: 0.5
    is_reverse: false
    is_mirror: true
    active_color_scheme_index: 1
    color_schemes: &id002
    - - red
      - green
      - blue
    - - '#2a04ff'
      - '#ff9604'
    - - '#02e6ff'
      - '#ff4a02'
    - - '#2bff01'
      - '#ff0127'
    - - '#fff700'
      - '#f700ff'
    - - red
    - - green
    - - blue
    - - yellow
    - - pink
    - - '#ee00ac'
      - blue
    - - '#BE008A'
      - green
  active_state_index: 1
  active_state:
    name: test
    active_audio_channel_index: 0
    audio_samples_filter_min: 0
    audio_samples_filter_max: 24
    audio_gain: 0.1
    audio_decay: 0.1
    division_value: 0
    active_visualizer_effect: spectrum
    max_brightness: 255
    time_interval: 0
    chunk_size: 50
    blur_value: 0.5
    is_reverse: false
    is_mirror: true
    active_color_scheme_index: 1
    color_schemes: *id002
    _number_of_color_schemes: 12
    _formatted_color_schemes:
    - - - 255
        - 0
        - 0
      - - 0
        - 128
        - 0
      - - 0
        - 0
        - 255
    - - - 42
        - 4
        - 255
      - - 255
        - 150
        - 4
    - - - 2
        - 230
        - 255
      - - 255
        - 74
        - 2
    - - - 43
        - 255
        - 1
      - - 255
        - 1
        - 39
    - - - 255
        - 247
        - 0
      - - 247
        - 0
        - 255
    - - - 255
        - 0
        - 0
    - - - 0
        - 128
        - 0
    - - - 0
        - 0
        - 255
    - - - 255
        - 255
        - 0
    - - - 255
        - 192
        - 203
    - - - 238
        - 0
        - 172
      - - 0
        - 0
        - 255
    - - - 190
        - 0
        - 138
      - - 0
        - 128
        - 0
- name: Circle
  serial_port_name: /dev/tty.usbserial-4
  is_online: false
  midi_ports_for_changing_mode:
  - Audio2Led ChangeMod Circle
  midi_ports_for_visualization:
  - Audio2Led Synth
  - LPK25
  original_physical_shape:
  - 60
  scene:
    shapes:
    - offset:
      - 45
      - 90
      pixel_range:
      - 0
      - 60
      svg_string: m56.75,0.75c30.939227,0 56,25.060773 56,56c0,30.939227 -25.060773,56
        -56,56c-30.939227,0 -56,-25.060773 -56,-56c0,-30.939227 25.060773,-56 56,-56z
    size:
      height: 170
      scale: 0.5
      width: 300
  states:
  - name: Circle bounce
    active_audio_channel_index: 0
    audio_samples_filter_min: 0
    audio_samples_filter_max: 3
    audio_gain: 0.1
    audio_decay: 0.1
    division_value: 0
    active_visualizer_effect: piano_scroll
    max_brightness: 138
    time_interval: 120
    chunk_size: 5
    blur_value: 0.6
    is_reverse: true
    is_mirror: true
    active_color_scheme_index: 10
    color_schemes:
    - - red
      - green
      - blue
    - - '#2a04ff'
      - '#ff9604'
    - - '#02e6ff'
      - '#ff4a02'
    - - '#2bff01'
      - '#ff0127'
    - - '#fff700'
      - '#f700ff'
    - - red
    - - green
    - - blue
    - - yellow
    - - pink
    - - '#ee00ac'
      - blue
    - - '#BE008A'
      - green
  - name: Circle 2
    active_audio_channel_index: 0
    audio_samples_filter_min: 0
    audio_samples_filter_max: 24
    audio_gain: 0.1
    audio_decay: 0.1
    division_value: 0
    active_visualizer_effect: energy
    max_brightness: 120
    time_interval: 120
    chunk_size: 5
    blur_value: 1.4
    is_reverse: false
    is_mirror: true
    active_color_scheme_index: 0
    color_schemes: &id003
    - - red
      - green
      - blue
    - - '#2a04ff'
      - '#ff9604'
    - - '#02e6ff'
      - '#ff4a02'
    - - '#2bff01'
      - '#ff0127'
    - - '#fff700'
      - '#f700ff'
    - - red
    - - green
    - - blue
    - - yellow
    - - pink
    - - '#ee00ac'
      - blue
    - - '#BE008A'
      - green
  active_state_index: 1
  active_state:
    name: Circle 2
    active_audio_channel_index: 0
    audio_samples_filter_min: 0
    audio_samples_filter_max: 24
    audio_gain: 0.1
    audio_decay: 0.1
    division_value: 0
    active_visualizer_effect: energy
    max_brightness: 120
    time_interval: 120
    chunk_size: 5
    blur_value: 1.4
    is_reverse: false
    is_mirror: true
    active_color_scheme_index: 0
    color_schemes: *id003
    _number_of_color_schemes: 12
    _formatted_color_schemes:
    - - - 255
        - 0
        - 0
      - - 0
        - 128
        - 0
      - - 0
        - 0
        - 255
    - - - 42
        - 4
        - 255
      - - 255
        - 150
        - 4
    - - - 2
        - 230
        - 255
      - - 255
        - 74
        - 2
    - - - 43
        - 255
        - 1
      - - 255
        - 1
        - 39
    - - - 255
        - 247
        - 0
      - - 247
        - 0
        - 255
    - - - 255
        - 0
        - 0
    - - - 0
        - 128
        - 0
    - - - 0
        - 0
        - 255
    - - - 255
        - 255
        - 0
    - - - 255
        - 192
        - 203
    - - - 238
        - 0
        - 172
      - - 0
        - 0
        - 255
    - - - 190
        - 0
        - 138
      - - 0
        - 128
        - 0
