--- # document start

################
# CONFIG FILE  #
################

desirated_framerate: 60
display_shell_interface: True
is_zmq_api_enabled: True

audio_ports:
  - name: Built-in Microphone
    min_frequency: 200
    max_frequency: 12000
  - name: Loopback Audio
    min_frequency: 200
    max_frequency: 12000

strips:
  - name: Default strip
    serial_port_name: /dev/tty.usbserial-A50285BI

    midi_ports_for_visualization:
      - 'Audio2Led Synth'
    midi_ports_for_changing_mode:
      - 'Audio2Led ChangeMod Center'

    active_state_index: 0

    physical_shape:
      - 80
      - 60
      - 40

  # - name: Default strip 2
  #   serial_port_name: /dev/tty.usbserial-A50285BI2
  #   midi_ports_for_visualization:
  #     - 'Audio2Led Synth'
  #   midi_ports_for_changing_mode:
  #     - 'Audio2Led ChangeMod Side'
  #   active_state_index: 1
  #   physical_shape:
  #     - 80
  #     - 80
  # - name: Default strip 3
  #   serial_port_name: /dev/tty.usbserial-A50285BI3
  #   midi_ports_for_visualization:
  #     - 'Audio2Led Synth'
  #   midi_ports_for_changing_mode:
  #     - 'Audio2Led ChangeMod Side'
  #   active_state_index: 0
  #   physical_shape:
  #     - 80
  #     - 80
  # - name: Default strip 4
  #   serial_port_name: /dev/tty.usbserial-A50285BI4
  #   midi_ports_for_visualization:
  #     - 'Audio2Led Synth'
  #   midi_ports_for_changing_mode:
  #     - 'Audio2Led ChangeMod Side'
  #   active_state_index: 0
  #   physical_shape:
  #     - 80
  #     - 80
  # - name: Default strip 5
  #   serial_port_name: /dev/tty.usbserial-A50285BI5
  #   midi_ports_for_visualization:
  #     - 'Audio2Led Synth'
  #   midi_ports_for_changing_mode:
  #     - 'Audio2Led ChangeMod Side'
  #   active_state_index: 0
  #   physical_shape:
  #     - 80
  #     - 80
states:
  - name: 'State 1'
    active_visualizer_effect: energy
    active_propagation_curve: ease_in

    active_audio_channel_index: 0
    audio_samples_filter_min: 0
    audio_samples_filter_max: 24

    active_color_scheme_index: 0
    color_schemes:
      - - red
        - green
        - blue
      - - red
        - green

    is_reverse: False
    is_mirror: False
    division_value: 1
    time_interval: 50
    chunk_size: 5
    blur_value: 4.0
    max_brightness: 55

  - name: 'State 2'
    active_visualizer_effect: scroll
    active_propagation_curve: ease_in

    active_audio_channel_index: 0
    audio_samples_filter_min: 0
    audio_samples_filter_max: 24

    active_color_scheme_index: 0
    color_schemes:
      - - red
        - blue
      - - red
        - green
        - blue
    is_reverse: True
    is_mirror: True
    division_value: 0
    time_interval: 150
    chunk_size: 50
    blur_value: 0.1
    max_brightness: 255
... # document end
