file_name: /Users/thibaudfrere/Documents/music-2-led/backend/CONFIG.yml
desirated_framerate: 60
display_shell_interface: false
is_zmq_api_enabled: true
audio_ports:
- max_frequency: 12000
  min_frequency: 200
  name: Loopback Audio
- max_frequency: 12000
  min_frequency: 200
  name: Built-in Microphone
strips:
- active_state_index: 0
  midi_ports_for_changing_mode:
  - Audio2Led ChangeMod Center
  midi_ports_for_visualization:
  - Audio2Led Synth
  name: Angles
  original_physical_shape:
  - 34
  - 52
  - 50
  scene:
    shapes:
    - offset:
      - 0
      - 0
      pixel_range:
      - 86
      - 136
      svg_string: M0,0 0,100 T75,175
    - offset:
      - 0
      - 0
      pixel_range:
      - 34
      - 86
      svg_string: M50,0 50,75 T100,125
    - offset:
      - 0
      - 0
      pixel_range:
      - 0
      - 34
      svg_string: M100,0 100,50 T125,75
    - offset:
      - 0
      - 0
      pixel_range:
      - 86
      - 136
      svg_string: M300,0 300,100 T225,175
    - offset:
      - 0
      - 0
      pixel_range:
      - 34
      - 86
      svg_string: M250,0 250,75 T200,125
    - offset:
      - 0
      - 0
      pixel_range:
      - 0
      - 34
      svg_string: M200,0 200,50 T175,75
    size:
      height: 170
      scale: 1.2
      width: 300
  serial_port_name: /dev/tty.usbserial-A50285BI
  states:
  - active_audio_channel_index: 0
    active_color_scheme_index: 0
    active_propagation_curve: ease_in
    active_visualizer_effect: piano_scroll
    audio_decay: 0.1
    audio_gain: 1
    audio_samples_filter_max: 24
    audio_samples_filter_min: 0
    blur_value: 1.0
    chunk_size: 50
    color_schemes:
    - - red
      - green
      - blue
    - - red
    - - green
    - - blue
    division_value: 0
    is_mirror: false
    is_reverse: false
    max_brightness: 100
    name: Classic energy 23
    time_interval: 10
  - active_audio_channel_index: 1
    active_color_scheme_index: 0
    active_propagation_curve: ease_in
    active_visualizer_effect: scroll
    audio_decay: 0.1
    audio_gain: 1
    audio_samples_filter_max: 24
    audio_samples_filter_min: 0
    blur_value: 0.1
    chunk_size: 50
    color_schemes:
    - - red
      - blue
    - - red
      - green
      - blue
    division_value: 0
    is_mirror: true
    is_reverse: false
    max_brightness: 100
    name: Classic scroll
    time_interval: 10
  - active_audio_channel_index: 0
    active_color_scheme_index: 0
    active_propagation_curve: ease_in
    active_visualizer_effect: piano_scroll
    audio_decay: 0.1
    audio_gain: 1
    audio_samples_filter_max: 24
    audio_samples_filter_min: 0
    blur_value: 1.1
    chunk_size: 50
    color_schemes:
    - - red
      - blue
    - - red
      - green
      - blue
    division_value: 0
    is_mirror: false
    is_reverse: false
    max_brightness: 100
    name: Piano note
    time_interval: 10
