--- # document start

################
# CONFIG FILE  #
################

desirated_framerate: 60
display_interface: true

audio_ports:
  - name: Built-in Microphone
    min_frequency: 200
    max_frequency: 12000

strips:
  - name: Default strip
    serial_port_name: /dev/tty.usbserial-A50285BI

    midi_ports_for_visualization:
      - "Audio2Led Synth"
    midi_ports_for_changing_mode:
      - "Audio2Led ChangeMod Center"

    active_state_index: 0

    physical_shape:
      - 80

states:
  - name: "Default State"
    active_visualizer_effect: energy
    active_propagation_curve: ease_in

    active_audio_channel_index: 0
    audio_samples_filter_min: 0
    audio_samples_filter_max: 24

    active_shape_index: 0
    shapes:
      - - 80
      - - 40
        - 40

    active_color_scheme_index: 0
    color_schemes:
      - - blue

    is_reverse: false
    is_mirror: false
    division_value: 1
    time_interval: 50
    chunk_size: 5
    blur_value: 4.0
    max_brightness: 55
... # document end
