audio_ports:
- max_frequency: 12000
  min_frequency: 200
  min_volume_threshold: 1.0e-07
  n_rolling_history: 4
  name: Loopback Audio
  number_of_audio_samples: 24
  sampling_rate: 44000
- max_frequency: 12000
  min_frequency: 200
  min_volume_threshold: 1.0e-07
  n_rolling_history: 4
  name: Built-in Microphone
  number_of_audio_samples: 24
  sampling_rate: 44000
delay_between_frames: 0.016666666666666666
desirated_framerate: 60
display_shell_interface: false
file_name: ./backend/NEWCONFIG.yml
is_zmq_api_enabled: true
number_of_audio_ports: 2
number_of_states: 10
number_of_strips: 1
states:
- &id001
  active_audio_channel_index: 0
  active_color_scheme_index: 0
  active_visualizer_effect: spectrum
  audio_decay: 0.1
  audio_gain: 1
  audio_samples_filter_max: 24
  audio_samples_filter_min: 0
  blur_value: 1.0
  chunk_size: 50
  color_schemes:
  - - red
    - green
    - blue
  - - red
    - green
  - - blue
  division_value: 0
  formatted_color_schemes:
  - - - 255
      - 0
      - 0
    - - 0
      - 128
      - 0
    - - 0
      - 0
      - 255
  - - - 255
      - 0
      - 0
    - - 0
      - 128
      - 0
  - - - 0
      - 0
      - 255
  is_mirror: false
  is_reverse: false
  max_brightness: 100
  name: Classic energy 2
  number_of_color_schemes: 3
  time_interval: 10
- active_audio_channel_index: 0
  active_color_scheme_index: 0
  active_visualizer_effect: channel_intensity
  audio_decay: 0.1
  audio_gain: 1
  audio_samples_filter_max: 24
  audio_samples_filter_min: 0
  blur_value: 4.0
  chunk_size: 5
  color_schemes:
  - - '#FF0000'
    - '#00FF00'
  division_value: 0
  formatted_color_schemes:
  - - - 255
      - 0
      - 0
    - - 0
      - 255
      - 0
  is_mirror: false
  is_reverse: false
  max_brightness: 120
  name: dududu
  number_of_color_schemes: 1
  time_interval: 120
- active_audio_channel_index: 0
  active_color_scheme_index: 0
  active_visualizer_effect: channel_flash
  audio_decay: 0.1
  audio_gain: 1
  audio_samples_filter_max: 24
  audio_samples_filter_min: 0
  blur_value: 4.0
  chunk_size: 5
  color_schemes:
  - - '#FF0000'
    - '#00FF00'
  division_value: 0
  formatted_color_schemes:
  - - - 255
      - 0
      - 0
    - - 0
      - 255
      - 0
  is_mirror: false
  is_reverse: false
  max_brightness: 120
  name: dwadawdawd
  number_of_color_schemes: 1
  time_interval: 120
strips:
- active_state: *id001
  active_state_index: 0
  is_online: false
  midi_logs:
  - note: 0
    port: Audio2Led ChangeMod Side
    type: note_on
    velocity: 127
  - action: updatestate
    data: Classic energy 2
    port: Audio2Led ChangeMod Side
    type: sysex
  - note: 9
    port: Audio2Led ChangeMod Side
    type: note_on
    velocity: 127
  - note: 4
    port: Audio2Led ChangeMod Side
    type: note_on
    velocity: 127
  - action: updatestate
    data: Classic energy 2
    port: Audio2Led ChangeMod Side
    type: sysex
  midi_ports_for_changing_mode:
  - Audio2Led ChangeMod Side
  midi_ports_for_visualization:
  - Audio2Led Synth
  name: Bar
  original_physical_shape: &id002
  - 80
  physical_shape:
    number_of_pixels: 80
    number_of_substrip: 1
    offsets:
    - 80
    shape: *id002
  scene:
    shapes:
    - offset:
      - 0
      - 0
      pixel_range:
      - 0
      - 80
      svg_string: M28.636 35.17H.142L20.207.415 40.272 35.17h-3.03
    - offset:
      - 0
      - 0
      pixel_range:
      - 0
      - 80
      svg_string: M75.842 34.245H54.309V.925h33.319v33.32h-3.19
    - offset:
      - 0
      - 0
      pixel_range:
      - 0
      - 80
      svg_string: M174.813 35.09l-10.728.055-7.112-21.525L175.243.205l18.404 13.235-6.896
        21.59-3.445.015
    - offset:
      - 0
      - 0
      pixel_range:
      - 0
      - 80
      svg_string: M122.79 34.845l-8.325.055-10.119-17.26L114.237.245l20.009-.13 10.118
        17.26-9.891 17.395-3.114.02
    size:
      height: 270
      scale: 3
      width: 750
  serial_port_name: /dev/tty.usbserial-A50285BI
  shapes:
  - number_of_pixels: 80
    number_of_substrip: 1
    offsets:
    - 80
    shape:
    - 80
  - number_of_pixels: 80
    number_of_substrip: 2
    offsets:
    - 40
    - 80
    shape:
    - 40
    - 40
  - number_of_pixels: 80
    number_of_substrip: 4
    offsets:
    - 20
    - 40
    - 60
    - 80
    shape:
    - 20
    - 20
    - 20
    - 20
  - number_of_pixels: 80
    number_of_substrip: 8
    offsets:
    - 10
    - 20
    - 30
    - 40
    - 50
    - 60
    - 70
    - 80
    shape:
    - 10
    - 10
    - 10
    - 10
    - 10
    - 10
    - 10
    - 10
timeSinceStart:
  end: 1594908497.740295
  start: 1594908497.0250828
